
[DefaultRake]
	"Can rake break blocks?" = true
	"Can rake climb?" = true
	#does it skip to day if you defeat the rake
	"Skip to day" = true
	"can rake teleport" = true

[Cave]
	"Can cave spawn" = true
	#how often the cave checks for spawning condition for the rake
	"Cave update check" = 1200.0

[BloodHourRake]
	"can bloodhour happen?" = true
	#the higher the number the lower the chance (cant be 1)
	"bloodhour chance" = 5.0
	"can bloodhour break blocks?" = true

["Other Stuff"]
	#(disables rake rewards) your a fucking pussy for turning this on
	"disable disable sleeping" = false
	#turning this on will play ambient music during the day
	"ambient day music" = false
	#the limit of how much scrap can spawn in a 512 block radius
	"scrap limit" = 10.0

["VisionHour Rake"]
	"visionhour chance" = 15.0
	"can vision hour break blocks" = true
	"can visionhour happen" = true

[BlackoutRake]
	"blackout chance" = 15.0
	"can blackout break blocks" = true
	"can blackout happen" = true

